### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by haidequanbu** [moon-hotel/BertWithPretrained#15]
机器配置：torch1.12.0+python3.8
运行原仓库的pretrain出错，报错如下：
Traceback (most recent call last):
  File "/root/Tasks/TaskForPretraining.py", line 305, in <module>
    train(config)
  File "/root/Tasks/TaskForPretraining.py", line 108, in train
    data_loader.load_train_val_test_data(test_file_path=config.test_file_path,
  File "/root/utils/create_pretraining_data.py", line 334, in load_train_val_test_data
    train_iter = DataLoader(train_data, batch_size=self.batch_size,
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 347, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
是不是torch版本有问题，3090的cuda只能11，torch好像最低1.9.0

**Comment by haidequanbu** [comment]
换了另外的v100显卡，torch版本和readme.md一致，还是爆同样的错

**Comment by haidequanbu** [comment]
文本中的代码有问题，经过修正，改成如下形式即可：/utils/create_pretraining_data.py的244-246行
        for paragraph in tqdm(paragraphs, ncols=80, desc=desc):
            paragraph=paragraph[0].split(".")# 遍历每个
            for i in range(len(paragraph) - 1):
<img width="528" alt="image" src="https://user-images.githubusercontent.com/67882439/205442957-47236f36-5512-4f68-98ec-00178607bdcb.png">
